Updating install method of Bluesky
Instead of using python setup.py install, a more complete way has been
found to just use pip install bluesky/

It was found that with the current setup.py file, the following error
occurs when running python setup.py install

    error: could not create '/share':
    Permission denied

This can be resolved by removing the '/' in the setup.py file but this
is unnecessary since pip install bluesky/ works.