Adding ruamel_yaml as dependency
This is due to a conda conflict

    ERROR: conda 4.7.10 requires ruamel_yaml>=0.11.14, which is not
    installed.

 Changes to be committed:
	modified:   environment.yml